### ISSUE TITLE
EPIC: Roadmap v1.0

### ISSUE THREAD

**Issue by pabloitu** [SCECcode/pycsep#269]
As mentioned in #239, API has stablized and we need to complete minor work for v1.0.0. Here we agree on the tasks, and issues, needed to be completed before the major release.

**Comment by pabloitu** [comment]
@wsavran @fabiolsilva @pjmaechling @serra314 @mherrmann3 @bayonato89 Need feedback on the roadmap, and include tasks suggestions in comments on this issue.

These are my work suggestion to be included in v1.0.0:

Features:
- [ ] #268 
- [ ] #232 

Refactoring:
- [ ] #263, which closes #260, #258
- [ ] Refactor core modules to harmonize function signatures and include type hinting
- [ ] Clean up unused functionality (e.g., documents.py, file.py, log.py)
- [ ] Refactor core-modules structure, to abstract any coupling between scores, tests and probability distributions.

Minor Fixes:
- [ ] #257
- [ ] #256 
- [ ] #216 
- [ ] #215
- [ ] #187 
- [ ] #176
- [ ] #90

Moderate Fixes:

- [ ] #255
- [ ] #226 
- [ ] #225

Fixes needing closing (?):

- [ ] #214
- [ ] #196 
- [ ] #195 
- [ ] #192 (discussion must be had)


Remaining open-issues could be dealt within the v1 versions.

**Comment by wsavran** [comment]
Hi @pabloitu,

Some thoughts here... Overall the roadmap to 1.0 looks good. We probably want to add some incremental releases in here, and we can iterate on during our next call. Also, I would elevate #255 to being a major issue. This has implications for most of the inner workings of the code and evaluations.
